### PR TITLE
Update the list of dependencies and build instructions.

### PR DESCRIPTION
**Pull request by mkhokhlov**
Hi Thomas,

These are the changes that helped me build and install the provider on Debian 10.3.

Thanks!

### CODE REVIEW

**Comment by mkhokhlov** [comment]
@googlebot I signed it!

**Comment by ThomasHabets** [comment]
Hmm. That shouldn't be needed for a release. I've not checked in the `configure` script and friends, but the tagged releases on github don't have them.

The README should probably reflect this, as a first step. Something like "If there is no `configure` script, then create it by `apt install [...]` and `./bootstrap.sh`.

**Comment by mkhokhlov** [comment]
I'm not sure I follow what you mean. This PR isn't about release instructions, it's about building right after cloning. Here's a scenario that follows the current build instructions:

```shell
$ cd `mktemp -d`
$ git clone https://github.com/ThomasHabets/simple-tpm-pk11.git
Cloning into 'simple-tpm-pk11'...
remote: Enumerating objects: 816, done.
remote: Total 816 (delta 0), reused 0 (delta 0), pack-reused 816
Receiving objects: 100% (816/816), 493.14 KiB | 161.00 KiB/s, done.
Resolving deltas: 100% (513/513), done.
$ ./configure && make && sudo make install
bash: ./configure: No such file or directory
```

**Comment by mkhokhlov** [comment]
Ping!

**Comment by ThomasHabets** [comment]
A release tarball should not require automake nor libtool, so I don't want it as part of the normal build&install flow.

I intend to rephrase, something like that, but have been nonstop busy this week. You can propose a rephrasing.

Short update. If I had more time I'd be more specific.

**Comment by mkhokhlov** [comment]
I'd be more than happy to rephrase, but I honestly don't understand the relation between the changes I'm proposing and the release tarball.

**Comment by ThomasHabets** [comment]
A release tarball, in my experience and opinion, should not require automake nor libtool. Tagged releases in github are at least currently not including the post-`./boostrap.sh` generated files.

In other words: We can't get away from the dependencies that the program or library inherently depends on (libraries and compilers). The *generated* files, like `./configure`, are extremely low dependency (e.g. a POSIX shell), and can't be made slimmer. A tarball release should therefore not require these extra `automake` and `libtool`.

One reason is that sometimes getting `automake` and `libtool` installed is a whole project in itself (e.g. a couple of extra steps on OpenBSD). And that's not something an end user should be required to do in order to just build, install, use.

Also the *version* of libtool often matters. If the end user is expected to install libtool, but runs on an old system without needed version... that should be the maintainer's problem, not the end user's.

**Comment by ThomasHabets** [comment]
I've updated the README with `bootstrap.sh` instructions.

**Comment by mkhokhlov** [comment]
Thanks, Thomas! Much appreciated!

**Pull request closed without merging**
